version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MYSQL_HOST=mysql
      - MYSQL_DBNAME=yourdbname
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: yourdbname
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:
